### ISSUE TITLE
Sample data file name: upper vs. lower case

### ISSUE THREAD

**Issue by mkgeneral** [InsightDataScience/border-crossing-analysis#1]
Hello,
the provided run.sh script points to Border_Crossing_Entry_**d**ata.csv with "d' in data as lower case.
However, sample data files (small and large from DOT) contain "D" (**D**ata) as upper case.

If shall script and sample input files are used as they were originally downloaded and then uploaded into Insight Coding Challenge tester website then the error message is displayed that the "input file cannot be found in repository".

Given Windows does not distinguish lower vs upper case in file names, this issue may not pop up until testing is performed in Insight environment.

Regards,
Maya

**Comment by emhoa** [comment]
Fixed the typo. Thanks
